### ISSUE TITLE
Disabled enchantments should not be added to loottables

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#119]

**Comment by oddlama** [comment]
Not sure why I thought this wasn't the case... Apparently it has always been like that.

**Comment by ryantheleach** [comment]
You thought it because I reported that players were obtaining enchantments, even though I had configured their base items, to be disabled.

**Comment by oddlama** [comment]
I vaguely remember something, but how did your players obtain the enchantments if they were disabled? I can see no obvious flaws in the registration logic...

**Comment by oddlama** [comment]
Anyhow I received a request to make recipes and loot-table registration optional. I'll make them fully configurable in the future but for now I just added an additional flag to disable either. Yet this is completely unrelated, so I'm still confused how the enchanted books could be obtained when the items were disabled

**Comment by ryantheleach** [comment]
The enchantments themselves were enabled as I was under the belief they were unobtainable outside of testing commands, as I had planned on having some of them obtainable at some point and wished to test them, put soulbound on kit items, etc.

In practice it turned out not to be the case, so I've had to yolo let players have a play with the enchants they found :P without testing.

**Comment by ryantheleach** [comment]
To be specific, 

```

item_ancient_tome:
  # Enable item ancient_tome
  # Default: true
  enabled: false

  book:
    # Enable 'book' item variant
    # Default: true
    enabled: false

  enchanted_book:
    # Enable 'enchanted_book' item variant
    # Default: true
    enabled: false

item_ancient_tome_of_knowledge:
  # Enable item ancient_tome_of_knowledge
  # Default: true
  enabled: false

  book:
    # Enable 'book' item variant
    # Default: true
    enabled: false

  enchanted_book:
    # Enable 'enchanted_book' item variant
    # Default: true
    enabled: false

item_ancient_tome_of_the_gods:
  # Enable item ancient_tome_of_the_gods
  # Default: true
  enabled: false

  book:
    # Enable 'book' item variant
    # Default: true
    enabled: false

  enchanted_book:
    # Enable 'enchanted_book' item variant
    # Default: true
    enabled: false
```
