### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by ayysmkz** [oddlama/vane#14]
I want to use vane plugins for a paper server, but some commands (vane and vanilla) are not working.
For example, when I issue the command /heads i get the response "error: permission denied!". Same with /gamemode

I have read through all of the vane config files, but cannot seem to find anything wrong. I have changed most of the values in the config files to try to fix it, but I can't find what's wrong.

The server is running paper-1.16.5-727, with vane 1.1.5. All the plugins are enabled except for vane-regions.

Here is the vane-permissions config.yml:

```
# The language for this module. The corresponding language file must be named
# lang-{lang}.yml. Specifying 'inherit' will load the value set for vane-core.
# Default: "inherit"
lang: "inherit"

# The module will only add functionality if this is set to true.
# Default: true
enabled: true

# Enable plugin metrics via bStats. You can opt-out here or via the global bStats
# configuration.
# Default: true
metrics_enabled: true

command_permission:
  # Enable command permission
  # Default: true
  enabled: true

command_vouch:
  # Enable command vouch
  # Default: true
  enabled: false

  # The group to assign to players when someone vouches for them.
  # Default: "user"
  vouch_group: "user"

# The permission group that will be given to new players.
# Default: "default"
default_group: "user"

# The permission groups. A player can have multiple permission groups assigned.
# Permission groups can inherit other permission groups by specifying
# vane.permissions.groups.<groupname> as a permission.
# Default:
#   default:
#     - bukkit.command.help
#     - bukkit.broadcast
#     - bukkit.broadcast.user
#   verified:
#     - vane.permissions.groups.user
#     - vane.permissions.commands.vouch
#   admin:
#     - vane.permissions.groups.verified
#     - vane.admin.bypass_spawn_protection
#     - vane.*.commands.*
#   user:
#     - vane.permissions.groups.default
#     - vane.admin.commands.spawn
#     - vane.admin.modify_world
#     - vane.regions.commands.region
#     - vane.trifles.commands.heads
groups:
  default:
    - bukkit.command.help
    - bukkit.broadcast
    - bukkit.broadcast.user
  verified:
    - vane.permissions.groups.user
    - vane.permissions.commands.vouch
  admin:
    - vane.permissions.groups.verified
    - vane.admin.bypass_spawn_protection
    - vane.*.commands.*
  user:
    - vane.permissions.groups.default
    - vane.admin.commands.spawn
    - vane.admin.modify_world
    - vane.regions.commands.region
    - vane.trifles.commands.heads

# Remove all default permissions to start with a clean preset.
# Default: true
remove_defaults: true

# DO NOT CHANGE! The version of this config file. Used to determine if the config
# needs to be updated.
version: 1
```
