### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Xanthus58** [oddlama/vane#213]
What is autostop and what does it do? I can't seem to find any real documentation about it either ingame, on modrinth or here on the wiki page.

**Comment by oddlama** [comment]
Well, it stops your server after a set amount of time if nobody's online. All the options (as opposed to player features) are usually documented in the config file instead of online:

```yaml
# plugins/vane-admin/config.yml

# ...
autostop:
  # Enable automatic server stop after certain time without online players.
  # Default: true
  enabled: true

  command_autostop:
    # Enable command autostop
    # Default: true
    enabled: true

  # Delay in seconds after which to stop the server.
  # Valid values: [0,)
  # Default: 1200
  delay: 1200
```
